# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.instagram.com	TRUE	/	TRUE	1655472512	csrftoken	Us38FPdLJrXQEvnC4QQVsbbaHbM4zcZm
#HttpOnly_.instagram.com	TRUE	/	TRUE	0	rur	ASH
.instagram.com	TRUE	/	TRUE	1687094912	mid	YMyfgQABAAHdl0wPEe9kh6svM1PK
.instagram.com	TRUE	/	TRUE	1631798912	ds_user_id	1949969475
#HttpOnly_.instagram.com	TRUE	/	TRUE	1655558912	sessionid	1949969475%3Am7THTs0h4X4Yqq%3A19
