# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.instagram.com	TRUE	/	TRUE	1655468959	csrftoken	noKkzK8UFovSN0JycCOvbwbmbHiV8WfK
#HttpOnly_.instagram.com	TRUE	/	TRUE	0	rur	ASH
.instagram.com	TRUE	/	TRUE	1687091359	mid	YMyRoAABAAFSOfjH0QUgV4Qi---o
.instagram.com	TRUE	/	TRUE	1631795359	ds_user_id	40390400243
#HttpOnly_.instagram.com	TRUE	/	TRUE	1655555359	sessionid	40390400243%3AyJAU51xDHakSyQ%3A16
